export { default as Welcome } from './Welcome';
export { default as Kanban } from './Kanban';
export { default as Tasks } from './Tasks';
export { default as Employees } from './Employees';
export { default as Calendar } from './Calendar';
export { default as NewUserFormPage } from './NewUserFormPage';
export { default as NewTaskFormPage } from './NewTaskFormPage';
export { default as EditUserPage } from './EditUserPage';
export { default as EditTaskPage } from './EditTaskPage';
export { default as Login } from './auth/Login';
// export { default as Area } from './Charts/Area';
// export { default as Bar } from './Charts/Bar';
// export { default as Financial } from './Charts/Financial';
// export { default as Line } from './Charts/Line';
// export { default as Pie } from './Charts/Pie';
// export { default as Pyramid } from './Charts/Pyramid';
// export { default as Stacked } from './Charts/Stacked';